name: Security

on:
  push:
    branches:
      - main
      - feat/encyclopedia
  pull_request:
    branches:
      - main
      - feat/encyclopedia
  schedule:
    - cron: '0 0 * * 0'  # Weekly on Sunday

jobs:
  security:
    name: Security Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.1'
          cache: true

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt json -out gosec-report.json ./...'
        continue-on-error: true

      - name: Upload Gosec Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: gosec-report
          path: gosec-report.json
          retention-days: 30

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
          category: 'trivy'

      - name: Check dependencies for vulnerabilities
        run: |
          go install github.com/sonatype-nexus-community/nancy@latest
          go list -json -m all | nancy sleuth

      - name: SAST with CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: 'go'
          queries: security-and-quality

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      - name: Security Summary
        if: always()
        run: |
          echo "Security Checks Completed"
          echo "============================="
          echo "✓ Gosec: Go security scanner"
          echo "✓ Trivy: Vulnerability scanner"
          echo "✓ Nancy: Dependency checker"
          echo "✓ CodeQL: Static analysis"
